DROP DATABASE IF EXISTS listDB;

CREATE DATABASE listDB;

DROP TABLE IF EXISTS tours;

CREATE TABLE tours (
    id INT(10) AUTO_INCREMENT NOT NULL,
    city VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    date INT(10) NOT NULL,
    time INT(10) NOT NULL,
    email VARCHAR(255) NOT NULL,
    budget INT(10) NOT NULL,
    PRIMARY KEY (id)
);